### ISSUE TITLE
Automated translations

### ISSUE THREAD

**Issue by kacperduras** [lvlup-pro/spawn-frontend-material#147]
Proposes the use of automatic translation from Google ([Google Text to Speech API](https://gist.github.com/alotaiba/1728771)) for other languages than English and Polish (these could be further locally). Therefore, the operation of multilingualism will definitely simpler :P

**For rectification**: it is the translation of language files, not the tickets content.

**Comment by SystemZ** [comment]
For current state of project, only EN and PL langs are needed.
Manual translations PR by humans are more correct and are accepted because it's a lot of work.

Let's talk about more translations after release of version 3.0, feel free to create this issue again then.
For the time being there are more important tasks like lack of pages and polishing.
Sorry for refuse but about 3months is not long time for this queue of tasks and we must plan carefully to make it to the deadline.
