### ISSUE TITLE
Tickets titles: escaping characters in backend

### ISSUE THREAD

**Issue by Libter** [lvlup-pro/spawn-frontend-material#76]
Why some characters (for example `'`) are escaped, and some more dangerous (`<`, `>`, `"`, etc.) are not?

Titles as text :
![image](https://cloud.githubusercontent.com/assets/5753763/23315968/d719b828-fac8-11e6-8f19-6629dc366a34.png)
Titles as html: 
![image](https://cloud.githubusercontent.com/assets/5753763/23315974/e75d157c-fac8-11e6-93dd-9b3f7d1cc670.png)
Neither way is good.

**Comment by SystemZ** [comment]
Let's sum this up and then decide if backend need changes.
Correct me if I'm wrong (slept recently only 1h).

With REST API based app, endpoint should return messages (strings) as it is.
Then frontend should escape characters to prevent XSS.
Backend should not alter message because it may prevent proper data analyzing.

By default Vue escapes html when using `{{ }}` so it should be ok.

**Comment by Libter** [comment]
`Backend should not alter message because it may prevent proper data analyzing.`
I totally agree, let's just don't escape `'` character.

**Comment by SystemZ** [comment]
To add confusion, v2 panel have it own quirks with escaping 😱
I need to add draft of submitting tickets on v3 to check if it's only v2 problem or v3 needs some work, currently it's hard to tell.
